### ISSUE TITLE
erro de classFactory

### ISSUE THREAD

**Issue by leocmarques** [DanielHSM/CurvaDeNivel#1]
Daniel, tudo bem?
primeiramente, parabéns pelo plugin, muito bom mesmo! Inclusive, acabei de publicar um vídeo no meu canal do Youtube (Descomplica QGIS) para divulgar seu trabalho e mostrar como utilizá-lo!

Estou passando para avisar que a versão 0.5 dele está com um erro no QGIS. Segue:
Impossível carregar complemento 'curva_de_nivel' Devido a um erro ao chamar o método Class Factory(). 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/leoma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\curva_de_nivel\__init__.py", line 38, in classFactory
    from .curva_de_nivel import CurvaDeNivelPlugin
  File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leoma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\curva_de_nivel\curva_de_nivel.py", line 44, in 
    from .curva_de_nivel_provider import CurvaDeNivelProvider
  File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leoma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\curva_de_nivel\curva_de_nivel_provider.py", line 37, in 
    from .curva_de_nivel_algorithm import CurvaDeNivelAlgorithm
  File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leoma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\curva_de_nivel\curva_de_nivel_algorithm.py", line 537
    match suavizar:
          ^
SyntaxError: invalid syntax

Antes da atualização, na versão 0.4, o plugin estava funcionando perfeitamente. Outros usuários reportaram o mesmo erro no meu vídeo publicado.
Grande abraço!

**Comment by DanielHSM** [comment]
Boa noite Léo.

Obrigado pelo retorno, já identifiquei o problema.
Nessa nova versão estou utilizando uma sintaxe (o *match *no caso) que só
está disponível no Python 3.10 em diante.
Você pode tentar atualizar o python utilizando a ferramenta OSGeo4W
<https://qgis.org/resources/installation-guide/#osgeo4w-installer>.
De qualquer forma vou modificar o software para não utilizar essa sintaxe e
aumentar a compatibilidade.
Assim que estiver pronto eu subo uma nova versão no repositório.

Atenciosamente,

Em seg., 4 de nov. de 2024, 16:22, leocmarques ***@***.***>
escreveu:

**Comment by DanielHSM** [comment]
Código do algoritmo de suavização alterado para compatibilizar com versões anteriores ao Python 3.10.
Estrutura _match_  (linha 537) substituída por _elif_.
